apiVersion: v1
kind: Service
metadata:
  name: appalerta-service
spec:
  # Usar LoadBalancer para provedores cloud ou NodePort para testes locais
  type: LoadBalancer 
  selector:
    app: appalerta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
